version: '3.3'

services:
  postgresql:
    image: postgres:15.1-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: colbooru
      POSTGRES_PASSWORD: ujCin5ZohRNEfEVZkwBsce
      POSTGRES_DB: colbooru
    volumes:
      - ./storage/postgres:/var/lib/postgresql/data

  minio:
    image: quay.io/minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: colbooru_minio
      MINIO_ROOT_PASSWORD: ZWTPvzARUTVc5FuMQUEeLQ
    volumes:
      - ./storage/minio:/data
    command:
      - server
      - /data
