spring:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/colbooru
    username: colbooru
    password: ujCin5ZohRNEfEVZkwBsce
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
  flyway:
    baseline-on-migrate: true

